name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Linting:
    name: Linting NodeJS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: node
      - name: Install Dependencies
        run: npx pnpm i --no-frozen-lockfile --strict-peer-dependencies=false
      - name: Run ESLint
        run: npx pnpm lint

  Building:
    name: Building NodeJS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: node
      - name: Install Dependencies
        run: npx pnpm i --no-frozen-lockfile --strict-peer-dependencies=false
      - name: Build code
        run: npx pnpm build
